[project]
name = "streamlit-wishlist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "polars>=1.13.1",
    "python-dotenv>=1.0.1",
    "streamlit>=1.40.1",
]
