[theme]
# Primary accent color for interactive elements
primaryColor = "#f5e0dc"

# Background color for main content area
backgroundColor = "#1e1e2e"

# Backgorund color used for sidebar/interactive widgets
secondaryBackgroundColor = "#11111b"

# Color used for almost all text
textColor = "#cdd6f4"

# font
font="monospace"
